sudo: required
services:
  - docker
before_install:
  - docker build -t infinitizon/docker-kube-stepheng-react -f Dockerfile.dev .

script:
  - docker run infinitizon/docker-kube-stepheng-react npm run test -- --coverage